Repository web42serv/cgi_letsgo, pull requests merged in 2023-09, with the labels that each got.

#6 🔨 Fix: cgi 실행 오류
  bb.conf
  html/cgi.py
  html/cgi0.py
  html/cgitest.py
  html/cgitest2.py
  inc/CgiHandler.hpp
  inc/Response.hpp
  src/CgiHandler.cpp
  src/Response.cpp
Labels: 🐞 Bug, ✨ Feature

#7 🔨 Fix: 함수 반환 타입 불일치 해결
  inc/CgiHandler.hpp
  src/CgiHandler.cpp
Labels: 🐞 Bug

#11 ✨ Feat: query string parsing
  html/cgitest3.py
  inc/CgiHandler.hpp
  src/CgiHandler.cpp
Labels: ✨ Feature

#17 ✨ Feat: delete method
  html/delete/d2.html
  inc/Response.hpp
  src/Response.cpp
Labels: ✨ Feature
